import fs from 'node:fs';
import path from 'node:path';
import type { ParsedFeature } from './types';
import { uniqueStepTemplates, pageObjectClassNameForFeature } from './PageObjectGenerator';

export interface StepGenerationOptions {
  stepsDir: string;
  dryRun?: boolean;
}

export type StepGenerationStatus = 'CREATED' | 'UPDATED' | 'UNCHANGED' | 'DRY_RUN';

export interface StepGenerationResult {
  filePath: string;
  status: StepGenerationStatus;
  stepCount: number;
}

/**
 * Generates the `steps/<feature>.steps.ts` file that binds every unique
 * step pattern in a feature to a call into its (never-overwritten) Page
 * Object. Step definitions never contain locators - they only delegate.
 * Fully deterministic and idempotent: re-run any number of times, the file
 * is only rewritten when the feature's steps actually changed.
 */
export function generateStepsForFeature(
  feature: ParsedFeature,
  options: StepGenerationOptions
): StepGenerationResult {
  const baseName = path.basename(feature.sourcePath, path.extname(feature.sourcePath));
  const filePath = path.join(options.stepsDir, `${baseName}.steps.ts`);
  const className = pageObjectClassNameForFeature(feature);
  const templates = uniqueStepTemplates(feature);

  const registrations = templates.map((template) => {
    const argNames = Array.from({ length: template.paramCount }, (_, i) => `arg${i + 1}`);
    const paramDecls = argNames.map((name) => `${name}: string`).join(', ');
    const fnParams = paramDecls ? `world: StepWorld, ${paramDecls}` : 'world: StepWorld';
    const escapedPattern = template.pattern.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

    return [
      `defineStep('${escapedPattern}', async (${fnParams}) => {`,
      `  const page = new ${className}(world.page);`,
      `  await page.${template.methodName}(${argNames.join(', ')});`,
      `});`,
    ].join('\n');
  });

  const content =
    [
      `// Generated by the framework's deterministic StepGenerator.`,
      `// Implement behavior in the Page Object, not here: ../src/pages/generated/${className}.ts`,
      `import { createStepRegistry, type StepWorld } from '../src/bdd/StepRegistry';`,
      `import { ${className} } from '../src/pages/generated/${className}';`,
      '',
      `// A registry scoped to this feature only - see StepRegistry.ts for why`,
      `// this isn't a shared global singleton.`,
      `export const { registry: stepRegistry, defineStep } = createStepRegistry();`,
      '',
      registrations.length > 0 ? registrations.join('\n\n') : '// No steps in this feature yet.',
    ].join('\n') + '\n';

  if (options.dryRun) {
    return { filePath, status: 'DRY_RUN', stepCount: templates.length };
  }

  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : null;
  if (existing === content) {
    return { filePath, status: 'UNCHANGED', stepCount: templates.length };
  }

  fs.mkdirSync(options.stepsDir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');

  return {
    filePath,
    status: existing === null ? 'CREATED' : 'UPDATED',
    stepCount: templates.length,
  };
}
