import type { Page } from '@playwright/test';
import { stepPatternToRegex } from './stepTemplate';
import { FrameworkError } from '../core/FrameworkError';

export interface StepWorld {
  page: Page;
}

export type StepHandler = (world: StepWorld, ...args: string[]) => Promise<void>;

interface RegisteredStep {
  pattern: string;
  regex: RegExp;
  handler: StepHandler;
}

/**
 * Registry of step definitions for a single feature. Each generated
 * `steps/*.steps.ts` file creates its own instance via `createStepRegistry()`
 * rather than sharing one global singleton - two features that happen to
 * use identical step text (e.g. every feature generated by the mock AI
 * provider) must never shadow each other's Page Object, even when
 * Playwright runs multiple spec files in the same worker process.
 * ScenarioRunner is given the matching registry explicitly and reads from
 * it to execute a scenario's raw step texts.
 */
export class StepRegistry {
  private readonly steps: RegisteredStep[] = [];

  define(pattern: string, handler: StepHandler): void {
    this.steps.push({ pattern, regex: stepPatternToRegex(pattern), handler });
  }

  find(stepText: string): { handler: StepHandler; args: string[] } {
    for (const step of this.steps) {
      const match = step.regex.exec(stepText);
      if (match) {
        return { handler: step.handler, args: match.slice(1) };
      }
    }
    throw new FrameworkError({
      stage: 'STEP_EXECUTION',
      message: `No step definition matches: "${stepText}"`,
      possibleCause:
        'The step definitions file for this feature was not generated, not imported, or the feature text changed after step generation.',
      recommendedAction: 'Run `npm run generate:steps` and re-import the generated steps file.',
    });
  }

  reset(): void {
    this.steps.length = 0;
  }
}

/**
 * Creates a fresh, standalone registry plus a `defineStep` bound to it.
 * Generated steps files use this instead of a shared global singleton -
 * see the class doc above for why.
 */
export function createStepRegistry(): {
  registry: StepRegistry;
  defineStep: (pattern: string, handler: StepHandler) => void;
} {
  const registry = new StepRegistry();
  return { registry, defineStep: (pattern, handler) => registry.define(pattern, handler) };
}
