# Generated by Claude Code (acting as the AI provider) from requirements/BATD.md.
# Target-URL: https://stage.hyundai.com.au/au/en/book-a-test-drive
Feature: Book a Test Drive
  A customer should be able to book a test drive for a specific model and
  powertrain by providing their location and contact details.

  Scenario: Booking a KONA Hybrid test drive at postcode 2000 with valid contact details and a selected purchase timeframe submits successfully and shows a confirmation message
    Given the requirement "Book a Test Drive" is ready to be tested
    When the following condition is evaluated: "Booking a KONA Hybrid test drive at postcode 2000 with valid contact details and a selected purchase timeframe submits successfully and shows a confirmation message."
    Then the expected outcome is satisfied
