# Generated by Claude Code (acting as the AI provider) from requirements/Ownership.md.
# Target-URL: https://dev.hyundai.com.au/au/en/crm-ownership-update
Feature: CRM Ownership Update
  Successful Ownership Update with valid date

  Scenario: Form is submitted successfully. The payload contains OwnershipEndDate__c in a valid date format (e.g., YYYY-MM-DD).
    Given the requirement "CRM Ownership Update" is ready to be tested
    When the following condition is evaluated: "Add VIN KMHJT81BLCU374044, click Check, select No to Do you still own this vehicle?, fill in all required fields, select a valid Month and Year for when the vehicle was sold, and submit the form."
    Then the expected outcome is satisfied
