import type { AIProvider } from '../AIProvider';
import type {
  AIRequest,
  AIResponse,
  StructuredAIRequest,
  LocatorContext,
  AISuggestedLocator,
  FailureAnalysis,
  HealingContext,
  HealingSuggestion,
} from '../types';
import type {
  RequirementInput,
  GeneratedFeature,
  ParsedFeature,
  GeneratedSteps,
} from '../../bdd/types';
import type { TestFailure } from '../../execution/TestFailure';
import type { LocatorDefinition } from '../../locator/LocatorDefinition';
import { extractIntendedTargetName } from '../../locator/actionText';
import { parsePlaywrightError } from '../../execution/PlaywrightErrorParser';
import { FrameworkError } from '../../core/FrameworkError';

/**
 * Cheap, honest heuristic name corrections for a known-bad locator name -
 * strip common suffixes a typo/stale-copy might have introduced. This is
 * NOT semantic understanding; it is one candidate-generation strategy among
 * several the framework supports (see docs/healing.md), and every result
 * still requires validation before it is trusted.
 */
function nameVariants(name: string): string[] {
  const variants = new Set<string>();
  if (/ed$/i.test(name)) variants.add(name.replace(/ed$/i, ''));
  if (/ing$/i.test(name)) variants.add(name.replace(/ing$/i, ''));
  if (/s$/i.test(name) && !/ss$/i.test(name)) variants.add(name.replace(/s$/i, ''));
  variants.delete(name);
  return [...variants];
}

/**
 * Deterministic, offline AI provider used to verify the framework's
 * generation/validation/execution pipeline without any real AI dependency.
 *
 * THIS IS A MOCK. It never calls a real model, and its output must never be
 * presented as if a real AI produced it - every artifact it writes is
 * labeled "Generated by MOCK AI provider".
 */
export class MockAIProvider implements AIProvider {
  readonly name = 'mock';

  async generate(request: AIRequest): Promise<AIResponse> {
    return {
      text: `MOCK response for prompt: ${request.prompt.slice(0, 120)}`,
    };
  }

  async generateStructured<T>(request: StructuredAIRequest, _schema: unknown): Promise<T> {
    throw new FrameworkError({
      stage: 'AI_GENERATION',
      message: `MockAIProvider does not implement generic generateStructured() (purpose: "${request.purpose}").`,
      possibleCause: 'The mock provider only implements the dedicated AIProvider methods.',
      recommendedAction:
        'Call a dedicated method (generateFeature, suggestLocator, ...), or configure a real AI provider for arbitrary structured generation.',
    });
  }

  async generateFeature(input: RequirementInput): Promise<GeneratedFeature> {
    const criteria =
      input.acceptanceCriteria.length > 0
        ? input.acceptanceCriteria
        : ['The requirement is satisfied'];

    const scenarios = criteria.map((criterion) => {
      const name = criterion.replace(/\.$/, '').trim();
      const escaped = criterion.replace(/"/g, '\\"').trim();
      return [
        `  Scenario: ${name}`,
        `    Given the requirement "${input.title}" is ready to be tested`,
        `    When the following condition is evaluated: "${escaped}"`,
        `    Then the expected outcome is satisfied`,
      ].join('\n');
    });

    const descriptionLines = input.description
      .trim()
      .split('\n')
      .map((line) => `  ${line}`.trimEnd())
      .join('\n');

    const content =
      [
        `# Generated by MOCK AI provider - for framework verification only. Do not treat as production coverage.`,
        ...(input.targetUrl ? [`# Target-URL: ${input.targetUrl}`] : []),
        `Feature: ${input.title}`,
        descriptionLines,
        '',
        scenarios.join('\n\n'),
      ]
        .filter((section) => section.length > 0)
        .join('\n') + '\n';

    return { title: input.title, content };
  }

  async generateStepDefinitions(feature: ParsedFeature): Promise<GeneratedSteps> {
    const coveredSteps = Array.from(new Set(feature.scenarios.flatMap((s) => s.steps)));
    const content = `// MOCK suggestion only - the framework's deterministic StepGenerator is authoritative.\n// Feature: ${feature.title}\n`;
    return { content, coveredSteps };
  }

  async suggestLocator(context: LocatorContext): Promise<AISuggestedLocator[]> {
    const previousLocator = context.previousLocator;
    if (previousLocator?.name) {
      const badName = previousLocator.name;
      const variants = nameVariants(badName);

      if (variants.length > 0) {
        return variants.map((name, index) => ({
          locator: { ...previousLocator, name },
          strategy: previousLocator.strategy,
          confidence: Math.max(0.3, 0.7 - index * 0.15),
          reason: `MOCK heuristic correction of previously-failing locator name "${badName}" -> "${name}". Requires validation before use.`,
        }));
      }
    }

    const name = extractIntendedTargetName(context.intendedAction);
    const locator: LocatorDefinition = {
      strategy: 'role',
      value: 'button',
      name,
    };

    return [
      {
        locator,
        strategy: 'role',
        confidence: 0.5,
        reason: `MOCK suggestion derived from the intended action text "${context.intendedAction}". Requires validation before use.`,
      },
    ];
  }

  async analyzeFailure(failure: TestFailure): Promise<FailureAnalysis> {
    const parsed = parsePlaywrightError(failure.error);

    return {
      isLocatorFailure: parsed.isLocatorRelated,
      suspectedElement: parsed.locator?.name ?? parsed.locator?.value,
      intendedAction: failure.scenario,
      previousLocator: parsed.locator,
      actionVerb: parsed.actionVerb,
      summary: parsed.isLocatorRelated
        ? `MOCK analysis: error text matched locator-failure heuristics for "${failure.testName}"${
            parsed.locator
              ? ` (locator: ${parsed.locator.strategy}="${parsed.locator.name ?? parsed.locator.value}")`
              : ''
          }.`
        : `MOCK analysis: error text did not match known locator-failure heuristics (${failure.testName}).`,
    };
  }

  async generateHealingSuggestion(context: HealingContext): Promise<HealingSuggestion> {
    const candidates = await this.suggestLocator(context.locatorContext);
    return {
      candidates,
      reasoning: `MOCK healing suggestion based on failure analysis: ${context.analysis.summary}`,
    };
  }
}
