// Generated by the framework's deterministic StepGenerator.
// Implement behavior in the Page Object, not here: ../src/pages/generated/OwnershipPage.ts
import { createStepRegistry, type StepWorld } from '../src/bdd/StepRegistry';
import { OwnershipPage } from '../src/pages/generated/OwnershipPage';

// A registry scoped to this feature only - see StepRegistry.ts for why
// this isn't a shared global singleton.
export const { registry: stepRegistry, defineStep } = createStepRegistry();

defineStep('the requirement {string} is ready to be tested', async (world: StepWorld, arg1: string) => {
  const page = new OwnershipPage(world.page);
  await page.theRequirementIsReadyToBeTested(arg1);
});

defineStep('the following condition is evaluated: {string}', async (world: StepWorld, arg1: string) => {
  const page = new OwnershipPage(world.page);
  await page.theFollowingConditionIsEvaluated(arg1);
});

defineStep('the expected outcome is satisfied', async (world: StepWorld) => {
  const page = new OwnershipPage(world.page);
  await page.theExpectedOutcomeIsSatisfied();
});
